Args = --no-fallback \
       -H:+ReportExceptionStackTraces \
       --enable-url-protocols=http,https \
       --initialize-at-build-time=org.slf4j \
       --initialize-at-run-time=com.google.gson.internal.UnsafeAllocator
